---
eck-elasticsearch:
  fullnameOverride: monitoring
  version: 8.17.4
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: monitoring
    logs:
      elasticsearchRefs:
        - name: monitoring
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 1
                  memory: 2Gi
                limits:
                  memory: 2Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
            storageClassName: managed-csi-premium
eck-kibana:
  fullnameOverride: monitoring
  version: 8.17.4
  elasticsearchRef:
    name: monitoring
  count: 1
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              memory: 1Gi
  config:
    server.publicBaseUrl: https://monitoring.foo.com  # Replaced in the deploy script.
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "https"
    pathType: Prefix
    hosts:
      - host: monitoring.foo.com  # Replaced in the deploy script.
        paths: /
