---
apiVersion: v1
kind: Service
metadata:
  name: prd-es-ingest-http
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: "prd"
    elasticsearch.k8s.elastic.co/node-ingest: "true"
  type: LoadBalancer
